name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REF: ${{ github.ref }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
