name: Build and Deployment

on:
  workflow_dispatch:
  push:
  pull_request:
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build:
    name: Build and Deployment
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REF: ${{ github.ref }}
      GITHUB_SHA: ${{ github.sha }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Cache ris4fun compile code
        id: docusaurus-rise4fun-compile-code
        uses: actions/cache@v3
        with:
          path: website/.docusaurus/docusaurus-remark-plugin-compile-code/
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Build all
        run: yarn build

      - name: semantic release prep
        run: yarn add -D -W semantic-release semantic-release-monorepo @semantic-release/git
        if: github.ref == 'refs/heads/main'
        
      - name: semantic release
        run: yarn workspaces run semantic-release -e semantic-release-monorepo 
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
          force_orphan: true
